server:
  port: 8080

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autotest
    username: root
    password: 123

  mybatis:
    type-aliases-package: com.hdn.model
    mapper-location:
      - mapper/*